app:
  # name: "" # Optional, default: "wakarimi-authentication"
  # env: "" # Optional, default: "dev"
  # logging_level: "" # Optional, default: "INFO"
  # version: "" # Optional, default: "v1"
  refresh_key: "qwerty01"
  access_key: "qwerty02"

http:
  host: "localhost"
  port: "8020"
  # read_timeout: "" # Optional, default: "1s"
  # write_timeout: "" # Optional, default: "1s"

db:
  host: "localhost"
  port: "5432"
  name: "dbname"
  user: "dbuser"
  password: "dbpassword"
  # read_timeout: "" # Optional, default: "1s"
  # write_timeout: "" # Optional, default: "1s"
  # charset: "" # Optional, default: "UTF-8"
  # migration_path: "" # Optional, default: "./internal/store/pgsqlx_repo/migration"

