basePath: /api/auth
definitions:
  account_handler.createRequest:
    properties:
      password:
        description: Password for logging into your account
        type: string
      username:
        description: Desired username
        type: string
    required:
    - password
    - username
    type: object
  response.Error:
    properties:
      message:
        description: Human-readable error message
        type: string
      reason:
        description: Internal error description
        type: string
    type: object
host: localhost:8020
info:
  contact:
    email: zalimannard@mail.ru
    name: Dmitry Kolesnikov (Zalimannard)
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Wakarimi Authentication API
  version: "0.5"
paths:
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - default: en-US
        description: Language preference
        in: header
        name: Produce-Language
        type: string
      - description: Account credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/account_handler.createRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Failed to encode request; Validation failed for request
          schema:
            $ref: '#/definitions/response.Error'
        "409":
          description: Username is already taken
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Creates an account
      tags:
      - Accounts
swagger: "2.0"
