basePath: /api
definitions:
  handlers.RegisterUserRequest:
    properties:
      password:
        description: |-
          Password of the user to be registered.
          Required: true
          Example: querty01
        maxLength: 50
        minLength: 8
        type: string
      username:
        description: |-
          Username of the user to be registered.
          Required: true
          Example: Zalimannard
        maxLength: 30
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
  types.Error:
    properties:
      error:
        description: |-
          The error message.
          Example: User already exists
        type: string
    required:
    - error
    type: object
host: localhost:8020
info:
  contact:
    email: zalimannard@mail.ru
    name: Zalimannard
  description: This is the authentication service for Wakarimi.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Wakarimi Authentication API
  version: "0.0"
paths:
  /register/user:
    post:
      consumes:
      - application/json
      description: Register a new user with the input payload
      parameters:
      - description: Register payload
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Ok.
        "400":
          description: Error.
          schema:
            $ref: '#/definitions/types.Error'
        "500":
          description: Error.
          schema:
            $ref: '#/definitions/types.Error'
      summary: Register a new user
swagger: "2.0"
